name: build and test

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.vb'
    - '**.vbproj'
    - '*.sln'
    - '*.sou'
    - '.github/workflows/test.yml'

jobs:
  build-and-test:

    name: Build & Test on ${{matrix.os}} & .NET ${{ matrix.dotnet }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
#          - ubuntu-latest
          - windows-latest
#          - macOS-latest
        dotnet: 
          - '5.0.x'
          - '6.0.x'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
